apiVersion: v1
kind: Service
metadata:
 name: customer360-service1
 labels:
   name: customer360-service1
spec:
 type: NodePort
 ports:
   - port: 8070
     targetPort: 8070
     nodePort: 32446
     
 selector:
   name: customer360-service1
